name: 'P&Co. Foundation'
favicon: null
layout_spectrum: 0.3225632579997182
typography_spectrum: 0.08606908284127712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6564673404209316
  lightness: 0.5837830652017146
  saturation: 0.4259900029283017
  rhythmicContrast: 0.08825882035307586
purpose: []
