name: 'P&Co. Foundation'
favicon: null
layout_spectrum: 0.09713
typography_spectrum: 0.08606908284127712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#02828e'
    - '#cbcbcb'
    - '#f7be4e'
    - '#5db0b8'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.08825882035307586
purpose: []
